### PR TITLE
first version of Dawid-Skene

### PR DESCRIPTION
**Pull request by bob-carpenter**
This PR contains 

* the Dawid-Skene model implemented in Stan with fixed priors for mixed panel data (not all annotators need to annotate each item),
* an R script to compute a simple co-annotation matrix among items (like a confusion matrix)
* an R script to run the Dawid-Skene model
* the basic annotation data prepared by @storopoli 

I checked that the results make sense, but there are no formal tests of anything.

### CODE REVIEW

**Comment by storopoli** [comment]
Bob, the terms of our use of Twitter data does not allow public posting of tweets (Liverpool rules).
Please remove the file `anno-model/data/brasil-covid-tweets.csv` and everything is fine to merge.
All other files are fine.

**Comment by bob-carpenter** [comment]
> our use of Twitter data does not allow public posting of tweets

Thanks for the heads up on tweets.    I'll just remove that column of data for the annotation task.   That'll make it feel like a typical Kaggle problem, where the data's disconnected from its original source.

@breckbaldwin:  Is there a plan for reproducibility (such as writing the API scripts to download the tweets for au ser) or is that just off the table for this project?

**Comment by bob-carpenter** [comment]
I'll

* delete my old repo entirely
* create a new PR without the offending text
* in the future, never touch any data on this project or any project involving Twitter

You may still need to follow these instructions on your repo to remove any offending data that would otherwise be permanent:

https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

I hate IP entanglements, which is why I try to do the right thing from the start.  Which makes it rather ironic this happened right after nitpicking about licensing.  Of course, no good deed goes unpunished.

**Comment by bob-carpenter** [comment]
Here's some more info on deleting as I'm not sure the above instructions work.  They seem to be sending mixed signals.

https://stackoverflow.com/questions/18318097/delete-a-closed-pull-request-from-github

Anyway, you have to do this to get rid of things on your side as the owner of the repo.  So sorry.

**Comment by bob-carpenter** [comment]
Just to confirm I put in the request with their portal to remove my PR permanentaly and also asked if you need to contact them to remove it on your side.  The portal for submitting requests is:

https://support.github.com/contact

**Comment by storopoli** [comment]
Closed in favor of #3

**Pull request closed without merging**
